[project]
name = "caracono"
description = "Demonstrates how to use and interact with variables in Clarity by caracono incrementing a 32-bit unsigned integer"
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.caracono]
path = "contracts/caracono.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
